# Generated by Django 3.0.6 on 2020-05-20 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='username', max_length=100, null=True)),
                ('email', models.EmailField(db_column='email', max_length=150, null=True, unique=True)),
                ('city', models.CharField(db_column='city', max_length=100, null=True)),
                ('company', models.CharField(db_column='company', max_length=100, null=True)),
                ('category', models.CharField(db_column='category', max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, db_column='user_id', default=uuid.uuid4, max_length=100, unique=True)),
            ],
        ),
    ]
